export const FETCH_RECIPES = 'FETCH_RECIPES';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_FANTASY = 'FETCH_FANTASY';
export const SET_NAVBAR_ACTIVE_ITEM = 'SET_NAVBAR_ACTIVE_ITEM';
